name: Build Cumulus Repo

env:
  DEFAULT_IMAGE: paritytech/srtool

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      srtool_image:
        description: The SRTOOL image to use
        default: paritytech/srtool
        required: false
      srtool_tag:
        description: The SRTOOL tag to use
        default: 1.60.0
        required: false

  schedule:
    - cron: "00 04 * * 1" # 4AM weekly on mondays

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
            - category: contracts
              runtime: contracts-rococo
            - category: assets
              runtime: statemine
            - category: assets
              runtime: statemint
            - category: starters
              runtime: shell
    name: Build ${{ matrix.category }}/${{ matrix.runtime }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: action

      - name: Checkout repo under test
        uses: actions/checkout@v3
        with:
          repository: paritytech/cumulus
          fetch-depth: 0
          path: repo

      - name: Srtool build
        id: srtool_build
        uses: ./action
        with:
          image: ${{ github.event.inputs.srtool_image || env.DEFAULT_IMAGE }}
          tag: ${{ github.event.inputs.srtool_tag }}
          chain: ${{ matrix.runtime }}
          runtime_dir: parachains/runtime/${{ matrix.category }}/${{ matrix.runtime }}
          workdir: "${{ github.workspace }}/repo"

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . | tee ${{ matrix.runtime }}-srtool-digest.json
          echo "Compact Runtime location    : ${{ steps.srtool_build.outputs.wasm }}"
          echo "Compressed Runtime location : ${{ steps.srtool_build.outputs.wasm_compressed }}"
